### ISSUE TITLE
Dependency on Forms 2.3.3.193

### ISSUE THREAD

**Issue by umaqs** [lassana/XamarinFormsPinView#1]
Error while installing in Xamarin platform PCL project:

> Could not install package 'FormsPinView 1.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			

NOTE : Installation successful in platform projects (Android, IOS, UWP)

**Comment by lassana** [comment]
Yeah, the library was built on `Profile 78`. Probably I can use more generic profile.

**Comment by lassana** [comment]
Should work with 1.0.1.
https://www.nuget.org/packages/FormsPinView/1.0.1
