### ISSUE TITLE
.NET standard 2.0 support

### ISSUE THREAD

**Issue by Sokoo92** [lassana/XamarinFormsPinView#3]
Hello,

I'd like to use this component, but it is giving me errors in my PCL(.NET standard library) after I installed it. Is there a possibility you can update this to work with .NET standard?

Thanks in advance,

Sokoo

**Comment by lassana** [comment]
I will definitely do this. Btw the current version from NuGet (1.0.1) works with .NET Standard 2.0 projects: https://github.com/lassana/XamarinFormsPinView/tree/a9d4bd06adf68c7adf3373a83e9ec6890ea14a28/FormsPinViewSample/FormsPinViewSample.Core

**Comment by Sokoo92** [comment]
Great! Thanks for the quick reply! :D Nice work on this component man, keep up the good work!

**Comment by lassana** [comment]
I've published [1.1.0](https://www.nuget.org/packages/FormsPinView/1.1.0) version which supports .NET Standard 2.0, PCL support is dropped.
