### ISSUE TITLE
Set pin length

### ISSUE THREAD

**Issue by Osmosis311** [lassana/XamarinFormsPinView#4]
Is it possible to set pin length after the object has been initialized?

**Comment by lassana** [comment]
I think it is. You might try to change the relevant value in the `PinViewModel`, and then raise `PropertyChanged` event for the `PinViewModel` property.

**Comment by Osmosis311** [comment]
I tried and it said the property is read-only (only at runtime).

**Comment by lassana** [comment]
Oh, I see, it's just not implemented in the library. I could do it in the next weekend, probably.

**Comment by Osmosis311** [comment]
Thank you!!!

This will allow me to re-use the same screen for two different scenarios,
when there's a 4-digit code or 6-digit code depending on the situation.

**Comment by lassana** [comment]
Done in the 2.0.0-pre1 version. See [updated readme](https://github.com/lassana/XamarinFormsPinView/blob/v2/README.md) for more info
