### ISSUE TITLE
Last dot is not filled in

### ISSUE THREAD

**Issue by apoorvvw** [lassana/XamarinFormsPinView#5]
I've implemented this and the functionality is working well, thanks for that by the way. However, the last dot is not being highlighted. You can see that in your gif too. 

If you have a hot fix, I can implement that locally instead of waiting for an update from your side; I have added the projects to my app instead to using the Nuget to try and fix this bug.

**Comment by apoorvvw** [comment]
I could fix this issue. 

In your PinViewModel constructor, in the KeyPressCommand implementation, make the following changes. 

* make command async
* Update display before clearing the Pin
* Add delay
* Update display after clearing the Pin for the error scenario

```C#
  KeyPressCommand = new Command<string>(async arg =>
  .
  .
  .
  if (EnteredPin.Count == TargetPinLength)
  {
      DisplayedTextUpdated?.Invoke(this, EventArgs.Empty);
      await Task.Delay(150);
      if (ValidatorFunc.Invoke(EnteredPin))
      {
          EnteredPin.Clear();
          Success?.Invoke(this, EventArgs.Empty);
      }
      else
      {
          EnteredPin.Clear();
          Error?.Invoke(this, EventArgs.Empty);
      }
      DisplayedTextUpdated?.Invoke(this, EventArgs.Empty);
  }
```

**Comment by lassana** [comment]
Done in the 2.0.0-pre1 version (`ClearAfterSuccess` property)
